export const SET_CATALOG_HEIGHT_BODY = "SET_CATALOG_HEIGHT_BODY";
export const SET_EQUIPMENTS_FROM_SERVER = "SET_EQUIPMENTS_FROM_SERVER";
export const SET_SELECTED_EQUIPMENT = "SET_SELECTED_EQUIPMENT";
export const SET_EQUIPMENT_TYPE_FOR_SORT = "SET_EQUIPMENT_TYPE_FOR_SORT";
export const SET_IS_CATALOG_BODY_OPEN = "SET_IS_CATALOG_BODY_OPEN";
export const SET_BASKET_EQUIMENT = "SET_BASKET_EQUIMENT";
export const DELETE_EQUIPMENT_FROM_BASKET_AT_INDEX= 'DELETE_EQUIPMENT_FROM_BASKET_AT_INDEX'

